baseURL = 'https://example.org/'
locale = 'en-us'
title = "CEO's Notes"
theme = 'PaperMod' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]

[[menu.main]]
	identifier = "home"
	name = "Beranda"
	url = "/"
	weight = 10

[[menu.main]]
	identifier = "posts"
	name = "Artikel"
	url = "/posts/"
	weight = 20

[[menu.main]]
	identifier = "categories"
	name = "Kategori"
	url = "/categories/"
	weight = 20

[[menu.main]]
	identifier = "about"
	name = "Tentang"
	url = "/about/" # Pastikan Anda nanti membuat file content/about.md
	weight = 30
	
[taxonomies]
  category = "categories"
  tag = "tags"

